// This file is auto-generated by @hey-api/openapi-ts
import { client } from './client.gen';
export const apiAuctionsList = (options) => (options?.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/auctions/',
    ...options
});
export const apiAuctionsCreate = (options) => (options.client ?? client).post({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/auctions/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiAuctionsDestroy = (options) => (options.client ?? client).delete({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/auctions/{id}/',
    ...options
});
export const apiAuctionsRetrieve = (options) => (options.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/auctions/{id}/',
    ...options
});
export const apiAuctionsPartialUpdate = (options) => (options.client ?? client).patch({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/auctions/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiAuctionsUpdate = (options) => (options.client ?? client).put({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/auctions/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiBidsList = (options) => (options?.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/bids/',
    ...options
});
export const apiBidsCreate = (options) => (options.client ?? client).post({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/bids/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiBidsDestroy = (options) => (options.client ?? client).delete({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/bids/{id}/',
    ...options
});
export const apiBidsRetrieve = (options) => (options.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/bids/{id}/',
    ...options
});
export const apiBidsPartialUpdate = (options) => (options.client ?? client).patch({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/bids/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiBidsUpdate = (options) => (options.client ?? client).put({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/bids/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiCategoriesList = (options) => (options?.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/categories/',
    ...options
});
export const apiCategoriesCreate = (options) => (options.client ?? client).post({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/categories/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiCategoriesDestroy = (options) => (options.client ?? client).delete({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/categories/{id}/',
    ...options
});
export const apiCategoriesRetrieve = (options) => (options.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/categories/{id}/',
    ...options
});
export const apiCategoriesPartialUpdate = (options) => (options.client ?? client).patch({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/categories/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiCategoriesUpdate = (options) => (options.client ?? client).put({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/categories/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiItemsList = (options) => (options?.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/items/',
    ...options
});
export const apiItemsCreate = (options) => (options.client ?? client).post({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/items/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiItemsDestroy = (options) => (options.client ?? client).delete({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/items/{id}/',
    ...options
});
export const apiItemsRetrieve = (options) => (options.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/items/{id}/',
    ...options
});
export const apiItemsPartialUpdate = (options) => (options.client ?? client).patch({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/items/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
export const apiItemsUpdate = (options) => (options.client ?? client).put({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/items/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
/**
 * Public API view for creating (registering) a new user.
 */
export const apiRegisterCreate = (options) => (options.client ?? client).post({
    url: '/api/register/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
/**
 * Takes a set of user credentials and returns an access and refresh JSON web
 * token pair to prove the authentication of those credentials.
 */
export const apiTokenCreate = (options) => (options.client ?? client).post({
    url: '/api/token/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
 * token if the refresh token is valid.
 */
export const apiTokenRefreshCreate = (options) => (options.client ?? client).post({
    url: '/api/token/refresh/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
/**
 * API endpoint that allows users to be viewed or edited.
 */
export const apiUsersList = (options) => (options?.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/',
    ...options
});
/**
 * API endpoint that allows users to be viewed or edited.
 */
export const apiUsersCreate = (options) => (options.client ?? client).post({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
/**
 * Instead of deleting, this performs a "soft delete" by deactivating the user.
 */
export const apiUsersDestroy = (options) => (options.client ?? client).delete({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{id}/',
    ...options
});
/**
 * API endpoint that allows users to be viewed or edited.
 */
export const apiUsersRetrieve = (options) => (options.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{id}/',
    ...options
});
/**
 * API endpoint that allows users to be viewed or edited.
 */
export const apiUsersPartialUpdate = (options) => (options.client ?? client).patch({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
/**
 * API endpoint that allows users to be viewed or edited.
 */
export const apiUsersUpdate = (options) => (options.client ?? client).put({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
/**
 * API endpoint that allows users to be viewed or edited.
 */
export const apiUsersStatisticsRetrieve = (options) => (options.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{id}/statistics/',
    ...options
});
/**
 * API endpoint that allows users to be viewed or edited.
 */
export const apiUsersRankingRetrieve = (options) => (options?.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/ranking/',
    ...options
});
//# sourceMappingURL=sdk.gen.js.map